import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#930013",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d8e2ff",
        "primary-container": "#6ffbbe",
        "on-primary-fixed": "#002113",
        "surface-container-low": "#f8f9fa",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-container": "#410004",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdad7",
        "primary-fixed": "#6ffbbe",
        "surface": "#ffffff",
        "surface-bright": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#006c49",
        "on-surface-variant": "#495057",
        "on-background": "#1a1c1e",
        "on-primary-fixed-variant": "#005236",
        "tertiary": "#904a43",
        "inverse-surface": "#2f3033",
        "on-primary-container": "#002113",
        "secondary-fixed": "#d8e2ff",
        "surface-dim": "#d9d9d9",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb3ad",
        "inverse-primary": "#4edea3",
        "surface-variant": "#dfe2eb",
        "outline": "#73777f",
        "primary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#001a42",
        "primary": "#10b981", 
        "on-primary": "#ffffff",
        "on-error-container": "#410002",
        "on-surface": "#1a1c1e",
        "secondary": "#405aa9",
        "tertiary-container": "#ffda2",
        "surface-container": "#f0f2f1",
        "background": "#f8f9fa",
        "surface-container-high": "#e9ecef",
        "inverse-on-surface": "#f1f0f4",
        "on-secondary-fixed": "#001a42",
        "outline-variant": "#dee2e6",
        "on-tertiary-fixed": "#410004",
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
      },
    },
  },
  plugins: [],
};
export default config;
