import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#930013",
        "on-tertiary": "#68000a",
        "secondary-container": "#0566d9",
        "primary-container": "#10b981",
        "on-primary-fixed": "#002113",
        "surface-container-low": "#1c1b1b",
        "on-error": "#690005",
        "on-secondary": "#002e6a",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-container": "#79000e",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ffdad7",
        "primary-fixed": "#6ffbbe",
        "surface": "#131313",
        "surface-bright": "#393939",
        "surface-container-highest": "#353534",
        "surface-tint": "#4edea3",
        "on-surface-variant": "#bbcabf",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#005236",
        "tertiary": "#ffb3ad",
        "inverse-surface": "#e5e2e1",
        "on-primary-container": "#00422b",
        "secondary-fixed": "#d8e2ff",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb3ad",
        "inverse-primary": "#006c49",
        "surface-variant": "#353534",
        "outline": "#86948a",
        "primary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#e6ecff",
        "primary": "#4edea3",
        "on-primary": "#003824",
        "on-error-container": "#ffdad6",
        "on-surface": "#e5e2e1",
        "secondary": "#adc6ff",
        "tertiary-container": "#ff7a73",
        "surface-container": "#201f1f",
        "background": "#131313",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#001a42",
        "outline-variant": "#3c4a42",
        "on-tertiary-fixed": "#410004",
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
      },
    },
  },
  plugins: [],
};
export default config;
