import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-tertiary": "var(--on-tertiary)",
        "secondary-container": "var(--secondary-container)",
        "primary-container": "var(--primary-container)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
        "on-error": "var(--on-error)",
        "on-secondary": "var(--on-secondary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "error": "var(--error)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "surface": "var(--surface)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-tint": "var(--surface-tint)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-background": "var(--on-background)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "tertiary": "var(--tertiary)",
        "inverse-surface": "var(--inverse-surface)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "error-container": "var(--error-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-variant": "var(--surface-variant)",
        "outline": "var(--outline)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-secondary-container": "var(--on-secondary-container)",
        "primary": "var(--primary)",
        "on-primary": "var(--on-primary)",
        "on-error-container": "var(--on-error-container)",
        "on-surface": "var(--on-surface)",
        "secondary": "var(--secondary)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container": "var(--surface-container)",
        "background": "var(--background)",
        "surface-container-high": "var(--surface-container-high)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
export default config;
